# Generated by Django 5.0.4 on 2024-04-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_orderitem_product_orderitem_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrders',
        ),
    ]
