# Generated by Django 5.0.4 on 2024-04-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='product_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
