# Generated by Django 5.0.4 on 2024-04-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_review_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ayurveda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.ayurveda'),
        ),
    ]
