# Generated by Django 5.0.4 on 2024-04-30 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skincare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinc_name', models.CharField(max_length=250)),
                ('skinc_image', models.ImageField(blank=True, null=True, upload_to='skincucts')),
                ('skinc_price', models.IntegerField()),
                ('skinc_descripton', models.TextField()),
                ('skinc_exp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
