# Generated by Django 5.0.4 on 2024-05-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_skincare'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='skincare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.skincare'),
        ),
    ]
