# Generated by Django 5.0.4 on 2024-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_skincare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
            ],
        ),
    ]
